# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  environment.systemPackages = with pkgs; [
    lz4
  ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "sd_mod" "sr_mod" "lz4" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    "zswap.enabled=1"
    "zswap.compressor=lz4"
    "zswap.max_pool_percent=20"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-5c2cf74e-5e3d-4bfa-9bcb-f268407eab66";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5c2cf74e-5e3d-4bfa-9bcb-f268407eab66".device = "/dev/disk/by-uuid/5c2cf74e-5e3d-4bfa-9bcb-f268407eab66";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B332-7ED6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
